### ISSUE TITLE
Expose a JavaScript function to read the proxyOwner from any proxy's storage

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/zos-lib#100]
See: https://github.com/zeppelinos/zos-lib/pull/36#issuecomment-388189205

**Comment by frangio** [comment]
I was convinced that we should leave `getProxyOwner` by @alcuadrado in https://github.com/zeppelinos/zos-lib/pull/36#discussion_r187810330:
>The helper is needed when BaseAppManager is not used, but it's somewhat obscure. If an app manager is used, the symmetry between getProxyOwner and getProxyImplementation would be helpful for newcomers.

Additionally we should provide the helper.
