### ISSUE TITLE
Add regression tests for different types of contract upgrades

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-lib#117]
As suggested by Nomic (https://github.com/zeppelinos/zos-lib/pull/102) we should have regression tests to ensure different types of contract upgrades work fine, such as:
- can add/remove a function,
- can change a function signature,
- can add/remove fallback function.

They seem obvious given the current implementation but it would allow us to make changes to the `Proxy` family of contracts with confidence.

**Comment by filiplazovic** [comment]
Can i take this one?

**Comment by frangio** [comment]
@filiplazovic Sure!
