### ISSUE TITLE
Make Initializable dependency explicit in oz-zos contracts

### ISSUE THREAD

**Issue by nventuro** [zeppelinos/zos-lib#123]
Some openzeppelin-zos contracts, like [MintableToken](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/zos-release/contracts/token/ERC20/MintableToken.sol) have no `initialize` method on their definition, but they inherit from contracts that do have one (in this case, [Ownable](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/zos-release/contracts/ownership/Ownable.sol)). Therefore, a call to `initialize` (which is actually the base contract's method) is necessary to correctly setup the contract, but this is not obvious from the contract code, and requires a user of the library to inspect the whole inheritance tree in order to figure it out.

This also leads to confusing code, like in [DetailedMintableToken](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/zos-release/contracts/token/ERC20/DetailedMintableToken.sol), where `Ownable.initialize` is called, despite `DetailedMintableToken` does directly inheriting from `Ownable`. This is enforced by the Solidity compiler, which will not compile a `MintableToken.initialize` call.

A suggested practice to improve readability and make it harder to miss the required `initialize` call would be to implement the method in all child contracts, calling their parent's implementation, i.e.:

```
contract MintableToken is Migratable, Ownable, StandardToken {
  function initialize(address _sender) isInitializer("MintableToken", "0") public {
    Ownable.initialize(_sender);
  }
  ...
}
```

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-solidity/commit/27a6a15d6623e5b894b61dbd5233fe9abb0fc222.

(Not released yet.)
