### ISSUE TITLE
Remove unused sender address from initialize calls

### ISSUE THREAD

**Issue by nventuro** [zeppelinos/zos-lib#124]
Some contracts (like [DetailedERC20](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/zos-release/contracts/token/ERC20/DetailedERC20.sol)) receive an unused `address _sender` argument in ther `initialize` method. This was proposed by @frangio for consistency, since all Solidity constructors have access to this value via `msg.sender`.

This causes not only confusion as to why this value is required, but also forces all contracts down the inheritance tree to also receive this parameter, and triggers Solidity warnings when compiling openzeppelin code:

```
openzeppelin-zos/contracts/token/ERC20/DetailedERC20.sol:11:23: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
  function initialize(address _sender, string _name, string _symbol, uint8 _decimals) public isInitializer("DetailedERC20", "0") {
                      ^-------------^
```

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-solidity/commit/dd6054efebeee9a49eecc150c3231df94f6c5e68.

(Not released yet.)
