### ISSUE TITLE
Review transaction timeout which can cause zos push to fail

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-lib#149]
`zos push` can sometimes fail by timing out with a message like "transaction wasn't processed in 240 seconds", even if the transaction is mined later. This can result in wasting ether unless one later manually modifies the `zos.network.json` file with the necessary values.

This error is emitted [here](https://github.com/trufflesuite/truffle-contract/blob/a407ce515763c4ad358c947bfbbeaed3ff1c88d3/contract.js#L192-L194) because the timeout by default is [240000](https://github.com/trufflesuite/truffle-contract/blob/a407ce515763c4ad358c947bfbbeaed3ff1c88d3/contract.js#L163-L167).

We can set `contract.synchronization_timeout = 0` in the following functions to remove the timeout entirely, or we could just set it to a larger value.

https://github.com/zeppelinos/zos-lib/blob/47edcb5d587e78c7beb99c883217baeedd1afc09/src/utils/Contracts.js#L34-L43

**Comment by spalladino** [comment]
Note that the timeout only affects transactions called on methods, *not* contract deployments.
