### ISSUE TITLE
Two copies of Ownable?

### ISSUE THREAD

**Issue by roschler** [zeppelinos/zos-lib#163]
During the process of installing ZOS it appears that both the `openzeppelin-solidity` and `openzeppelin-zos` packages get installed.  This is evident from the presence of both those packages in the resulting _node_modules_ directory _and_ by looking in the _package.json_ file in tutorials like the _Basil_ tutorial.  Unfortunately this leads to two copies of the `Ownable` contract being resident in a ZOS project:

```
./node_modules/openzeppelin-solidity/contracts/ownership/Ownable.sol
./node_modules/openzeppelin-zos/contracts/ownership/Ownable.sol
```
Given that the problem I'm currently having right now has to do with a **revert** error occurring during the _onlyOwner_ owner check that is part of the call to the **BasilERC721** contract created during the _Basil_ tutorial, is it possible this is the reason why?  I find it hard to believe the ZOS-LIB core code would make a mistake like passing the wrong _owner_ address to _proxied/logic-contract_ thereby creating the issue I'm having.  Given that I've also had the occasional problem during a _Truffle console_ compile as part of a debugging attempt, where it complained about the _Ownable_ contract being included **twice**, I'm wondering if this is the root cause of the issue I'm having?

I'm going to removing one of those _Ownable_ instance as an experiment.  I'm guessing it will just break everything, but it's worth a try.

**Comment by facuspagnuolo** [comment]
It shouldn't be a problem. However, you shouldn't be importing both contracts under the same symbol. 
OTOH, Truffle will complain because it cannot handle multiple contracts with the same name, to deal with that we have implemented [Contracts.js](https://github.com/zeppelinos/zos-lib/tree/master/src/utils/Contracts.js)

**Comment by roschler** [comment]
Thanks.
