### ISSUE TITLE
Ignore build files of ignored contracts when publishing

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos-lib#208]
Currently, we have a `prepack` NPM task that compiles all the contracts of the project. Some of these contracts (mocks) are being ignored, i.e. are not being published on every release. However, the `prepack` task is compiling those contracts and their respective build files are being published. We should ignore them too.

**Comment by spalladino** [comment]
The following line takes care of this: `grep -hoP '^\s*contract \K(\w+)' contracts/mocks/*.sol | sort | uniq | xargs -t -I% rm build/contracts/%.json`

**Comment by facuspagnuolo** [comment]
Closing in favour of https://github.com/zeppelinos/zos/issues/426
