### ISSUE TITLE
Handle multiple fallback providers

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos-lib#27]
Explore the idea of handling multiple fallback providers within a project controller. The idea would be to let the project owner decide whether to use zOS or another providers regulated by other tokens for example. 

There are many alternatives we can explore to implement this:
- We can implement a way to decide the fallback provider based on the given `distribution` and `version`
- We could also define a way to set priorities between different providers
- We may need another parameter besides `distribution` and `version` to tell the provider of the implementation

**Comment by spalladino** [comment]
Setting this for after MVP, we'd need to start first with at least one provider :-P

**Comment by facuspagnuolo** [comment]
Closing this one since we are already working on multiple dependencies :)
