### ISSUE TITLE
Store project name in ProjectController as a string instead of its hash

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-lib#39]
Wait until solc 0.4.22 is released which includes https://github.com/ethereum/solidity/pull/3308

**Comment by facuspagnuolo** [comment]
Related to https://github.com/zeppelinos/zos-lib/issues/162

**Comment by facuspagnuolo** [comment]
This issue is no longer true, we are not storing project names anymore. Additionally, the strings we are storing are not hashed. Closing.
