### ISSUE TITLE
Consider adding "hasImplementation" to the ContractProvider interface

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos-lib#43]
At the moment, BaseAppManager has the functions `getImplementation` and `getImplementationOrRevert`. The latter may seem redundant but exists to allow getImplementation to respond without throwing an error or reverting.

If this is considered redundant and is removed, there should be a way to make a query that doesnt throw an error such as `hasImplementation` in the ContractProvider interface.

**Comment by facuspagnuolo** [comment]
This is no longer true. The `getImplementationOrRevert` method has been removed. Given  `getImplementation` returns the zero-address if a requested implementation is not found, this functionality can be implemented client side.
