### ISSUE TITLE
Discuss if we should manage registering new package versions through the application manager

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos-lib#46]
Currently when we use a `PackagedAppManager` we have to register a new version in the `Package` and then ask the manager to upgrade each proxy. Discuss whether this functionality could be carried out by the manager.

~Additionally consider renaming `upgradeTo`  to `upgrade`~

**Comment by frangio** [comment]
:-1: A `Package` is independent from any `AppManager`. The relationship is one-to-many, possibly many-to-many in the future.
