### ISSUE TITLE
Consider using integers for migration ids

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-lib#56]
I think migration ids should be integers, because it communicates better their sequential nature.

https://github.com/zeppelinos/zos-lib/blob/0b8f1badfcdff52ad1483800a1456260968d2ff6/contracts/migrations/Migratable.sol#L5

**Comment by facuspagnuolo** [comment]
Agreed with @frangio offline to tackle this issue after the MVP

**Comment by facuspagnuolo** [comment]
Closing this issue since we dropped `Migratable`
