### ISSUE TITLE
Proposal for initializers and migrations

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-lib#61]
_:construction: This proposal is a work in progress._

@spalladino and I recently discussed a new approach to getting constructor code to run on a newly created proxy.

Currently, with the initializers implemented in the `Migratable` contract, the initializer code is stored like any other external function inside the contract bytecode. This initializer function has to be marked with the `isInitializer` modifier which will ensure it is only run once. Then it is called externally in the newly created proxy.

The new approach is inspired by how contract creation normally works in the EVM. Normally, the constructor code is not part of the bytecode that will be deployed. It is run at contract creation and then discarded.

We can somewhat emulate this by adding an additional parameter to the `UpgradeabilityProxy` constructor: an address that will be `delegatecall`ed during construction, which would only serve to initialize the necessary storage. This same argument can be added to the `_upgradeTo` function to implement migrations/[generalized constructors](https://github.com/zeppelinos/labs/issues/17#issuecomment-379083640). When not needed, the argument can be set to zero.

Thus, the run-only-once property of the initializer is enforced at the level of the proxy.

The address of initializer and migration contracts can be stored in the `ContractDirectory` for each of the provided contracts. In the case of migrations it may be necessary to store more than one migration contract, to be chosen depending on the previous implementation that is being switched out.

**Comment by facuspagnuolo** [comment]
@frangio this is how  https://github.com/zeppelinos/zos-lib/issues/50 can be implemented right?

**Comment by frangio** [comment]
More or less, yeah. I got excited and forgot to search before creating this issue. :sweat_smile:

**Comment by frangio** [comment]
We've been working on this proposal and built an initial implementation for constructors without arguments in the [`initializer_contracts`](https://github.com/zeppelinos/labs/tree/master/initializer_contracts) labs experiment.

As a next step we tackled constructors with arguments and ran into the difficulty that constructors read their arguments using `codecopy`, so this doesn't work for deploy-once constructors. A first workaround for this issue is proposed in https://github.com/zeppelinos/labs/pull/124 which deploys a new constructor for each instance of a Proxy. This turned out to be even more expensive than a traditional (non-upgradeable) deployment so we consider it prohibitive.

We're now looking into solving the problem in a cheaper way. From this last experiment it became obvious that we have to modify some code because a normal contract with a constructor uses `codecopy` to read its arguments. We now have to choose whether to modify source code or to modify bytecode. As a first step we want to try doing each of these alternatives by hand to evaluate the feasibility of doing the transformation automatically, and as a result decide which way to go based on a set of criteria that we've put together.

- *Gas cost.* 
- *Verifiability.* It doesn't seem to be possible to verify on Etherscan something that isn't exactly a Solidity-compiled program.
- *Robustness.* Resilience to changes in Solidity, solc, ABI, EVM.
- *Auditability.* The ability of the user to manually verify the correctness of the code we generate.
- *Portability.* EVM efforts ported to eWASM. Solidity efforts ported to other languages like Vyper, and at some point Rust, Kotlin, or whatever.
- *UX.*
- *Simplicity.*

@spalladino and I have already begun work on the next step of manually trying each alternative.

**Comment by facuspagnuolo** [comment]
Thanks for the update @frangio! Let's explore both alternatives, it sounds great :)

**Comment by frangio** [comment]
Closing in favor of https://github.com/zeppelinos/zos/issues/57.
