### ISSUE TITLE
Review naming

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-lib#68]
- [x] Consider renaming upgradeTo to upgrade in contracts
- [x] Review all other names in `zos-lib`
- [x] Review all other names in `zos-cli`
- [x] Replace all occurrences of `zeppelin_os` with `ZeppelinOS`

**Comment by maraoz** [comment]
All naming was reviewed, some changes pending implementation in https://github.com/zeppelinos/zos-cli/issues/42#issuecomment-389268667, but I'm closing this issue.
