### ISSUE TITLE
Discuss whether ImplementationDirectory should have a "developer" state variable

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-lib#69]
`address developer` is already present in kernel's [`Release`](https://github.com/zeppelinos/kernel/blob/c128069831d758ca72d39070b8a9cfafb3fdaaa4/contracts/Release.sol#L13).

Should we include this state variable in all `ImplementationDirectory`s?

**Comment by facuspagnuolo** [comment]
I do agree we should a developer field to implementation directories

**Comment by facuspagnuolo** [comment]
We've been discussing this with @frangio and @fiiiu offline. We concluded there is no need to have a separate address to keep track of the developer of an `ImplementationDirectory`, neither an alias like we are currently doing with the `Release` contract. Thus, we will remove the `Release` contract. 

If in a future we need a developer address, e.g. to distribute payouts from the Kernel, we think this data should be hold within the KernelRegistry
