### ISSUE TITLE
Document the reason for using initializers instead of constructors

### ISSUE THREAD

**Issue by elopio** [zeppelinos/zos-lib#89]
The post about proxy patterns briefly mentions that constructors can't be used because the proxy will not know about the variable values that are set by the constructors. This should be expanded, because it leaves more questions than answers.

We should mention things like when the  `Contract.new()` is called, the constructor is executed but the code for the constructor is not stored on the blockchain, so we can't call the constructor later as we can call the initialize function. When `Contract.at(proxy.address)` is called, this has a new storage space so the variables already initialized are not part of the proxied contract. Also, that it's not possible to copy the storage space of the contract to the proxy because it would be too expensive.

**Comment by elopio** [comment]
This could be documented as a blog post, or in the docs site. And the README can just link to it.

**Comment by fiiiu** [comment]
Closed by https://github.com/zeppelinos/zos-docs/pull/29.
