### ISSUE TITLE
Document why we can't remove state variables

### ISSUE THREAD

**Issue by elopio** [zeppelinos/zos-lib#90]
In the REAMDE, it says:

"Note that when we update our contract's code, we can't change its pre-existing storage structure. This means we can't remove any previously existing contract variable. We can, however, remove functions we don't want to use anymore [...]"

This should be expanded. First, we need to explain why we need to preserve the storage structure: if we remove variables, then the remaining ones will use the wrong address in memory. We should explain that the only thing that we must not do is to remove variables, but we can add new ones. Also, that we can add or remove functions, this is only for variables. 

About functions, @frangio mentioned that we might get in trouble if we are unlucky and get a collision on the initial bits of the hashes. We should mention this, and make recommendations to avoid it.

**Comment by fiiiu** [comment]
Closed by https://github.com/zeppelinos/zos-docs/pull/29.
