### ISSUE TITLE
Remove Babel dependency

### ISSUE THREAD

**Issue by frangio** [zeppelinos/zos-lib#94]
We're using it for ES6 modules and object spread syntax, and IMO it is not worth the additional complexity, indirection, and potential source of error.

**Comment by facuspagnuolo** [comment]
Related to https://github.com/zeppelinos/zos-cli/issues/15

**Comment by facuspagnuolo** [comment]
Let's make sure babel is not installed when `zos` is installed through NPM. We should only need it transpile ES6 before publishing

**Comment by facuspagnuolo** [comment]
We may re-consider this once https://github.com/trufflesuite/ganache-cli/pull/537 is released

**Comment by spalladino** [comment]
Disagree. Let's review the complexities added, but I don't see it as an issue, and being able to use latest js flavours is a win.

**Comment by facuspagnuolo** [comment]
Let's upgrade to the latest version of `ganache-cli`, babel shouldn't be a prod dependency anymore, and I'll be ok to have it as a dev one

**Comment by facuspagnuolo** [comment]
We decided to keep babel despite its complexity. Closing this issue.
